<?php

/**
 * @file bem_markup.module
 * Add BEM Style markup to to the classes_array
 */

/**
 * Implements hook_preprocess_node().
 *
 * Add markup to the node template
 */
function bem_markup_preprocess_node(&$vars) {
  if (isset($vars['elements']['#view_mode'])) {
    $view_mode = $vars['elements']['#view_mode'];
    $vars['classes_array'][] = 'node-' . $vars['type'] . '--' . str_replace('_', '-', $view_mode);
  }
}
